FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy application code
COPY . .

# Start development server
ENV NODE_ENV=development
EXPOSE 3000

CMD ["npm", "run", "dev"]
