groups:
  - name: vitalyst_alerts
    rules:
      - alert: HighRequestLatency
        expr: http_request_duration_seconds{quantile="0.9"} > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency on {{ $labels.instance }}"
          description: "90th percentile of request latency is above 1s"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 5m"

      - alert: Neo4jConnectionIssues
        expr: neo4j_connection_failures_total > 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Neo4j connection issues detected"
          description: "Database connection failures detected"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / process_memory_limit_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage above 80%"
